theme = "dracula"

[editor]
line-number = "relative"
shell = ["nu", "--stdin", "--config", "~/.config/nushell/pipes.nu", "-c"]
true-color = true
undercurl = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
S-ret = ":pipe-to zellij-repl"
"\\" = ":pipe-to zellij-repl"

