theme = "dracula"

[editor]
line-number = "absolute"
shell = ["nu", "--stdin", "--config", "~/.config/nushell/pipes.nu", "-c"]
true-color = true
undercurl = true
bufferline = "always"
auto-save.after-delay.enable = true

end-of-line-diagnostics = "error"
[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"\\" = ":pipe-to zellij-repl"
S-h = ":bp"
S-l = ":bn"

[keys.normal.space]
space = ":write"

[keys.normal.space.g]
f = "changed_file_picker"

