[[language]]
name = "julia"
auto-format = true

[language-server.julia]
command = "julia"
args = [
  "--sysimage=/home/sandy/dotfiles/juliasys/lsp.so",
  "--startup-file=no",
  "--history-file=no",
  "--quiet",
  "-e",
  "using LanguageServer; runserver()",
]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "quarto"
scope = "source.qmd"
language-id = "qmd"
injection-regex = "qmd"
file-types = ["qmd"]
indent = { tab-width = 2, unit = "  " }
grammar = "markdown"
block-comment-tokens = { start = "<!--", end = "-->" }
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "latex"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
executable = "latexmk"
pdfDirectory = "out"
args = [
  "-lualatex",
  "-outdir=out",
  "-interaction=nonstopmode",
  "-synctex=1",
  "-norc",
  "%f"
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true
