[[language]]
name = "julia"
auto-format = true

[language-server.julia]
command = "julia"
args = [
  "--sysimage=/home/sandy/dotfiles/juliasys/lsp.so",
  "--startup-file=no",
  "--history-file=no",
  "--quiet",
  "-e",
  "using LanguageServer; runserver()",
]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "quarto"
scope = "source.qmd"
language-id = "qmd"
injection-regex = "qmd"
file-types = ["qmd"]
indent = { tab-width = 2, unit = "  " }
grammar = "markdown"
block-comment-tokens = { start = "<!--", end = "-->" }
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
