[language-server.julia]
command = "julia"
args = [
  "--sysimage=/home/sandy/dotfiles/julia-sysimages/lsp.so",
  "--startup-file=no",
  "--history-file=no",
  "--quiet",
  "-e",
  "using LanguageServer; runserver()",
]
