[[language]]
name = "julia"
auto-format = true

[language-server.julia]
command = "julia"
args = [
  "--sysimage=/home/sandy/dotfiles/juliasys/lsp.so",
  "--startup-file=no",
  "--history-file=no",
  "--quiet",
  "-e",
  "using LanguageServer; runserver()",
]
