#!/bin/bash

yay -Sy --needed --noconfirm kanata-bin
stow --target="$HOME" .

sudo groupadd uinput
sudo usermod -aG input sandy
sudo usermod -aG uinput sandy

sudo touch /etc/udev/rules.d/99-input.rules
echo "KERNEL==\"uinput\", MODE=\"0660\", GROUP=\"uinput\", OPTIONS+=\"static_node=uinput\"" | sudo tee /etc/udev/rules.d/99-input.rules
sudo udevadm control --reload-rules && sudo udevadm trigger
ls -l /dev/uinput
echo "\n\ndid the above equal this?"
echo "crw-rw---- 1 root date uinput /dev/uinput"

sudo modprobe uinput

mkdir -p ~/.config/systemd/user
cp kanata.service ~/.config/systemd/user

systemctl --user daemon-reload
systemctl --user enable kanata.service
systemctl --user start kanata.service
systemctl --user status kanata.service
