#!/bin/bash

ide=(
    git
    stow
    man-db
    htop
    btop
    curl
    wget
    openssh
    github-cli
    git-delta
    unzip
    bat

    fd
    fzf
    ripgrep
    neofetch
    reflector

    fish
    carapace
    nushell

    zellij
    yazi
    broot
    helix
    
    starship
    zoxide
    lazygit
)

# raw install
./install/stow "${ide[@]}"
./install/yeah "${ide[@]}"

# update yazi
ya pack -i

# install zellij stuff
./zellij/.config/zellij/plug.sh

# broot install
broot --install
