#!/bin/bash

langs=(
    juliaup

    python
    python-pip
    uv

    marksman
    prettier
    pandoc

    quarto-cli-bin

    docker
    docker-compose
)

# raw install
./install/stow "${langs[@]}"
./install/yeah "${langs[@]}"

