#!/bin/bash

langs=(
    juliaup

    python
    python-pip
    python-poetry
    pyenv

    docker
    docker-compose
)

# raw install
./installers/stow "${langs[@]}"
./installers/yeah "${langs[@]}"

