---
# === PREREQUISITES ===

- name: "Arch | System update"
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  tags: [minimal, dev, full, always]

- name: "Arch | Install prerequisites"
  become: true
  community.general.pacman:
    name:
      - base-devel
      - git
    extra_args: --needed
  tags: [minimal, dev, full, always]

# === YAY SETUP ===

- name: "Arch | Create aur_builder user"
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
  tags: [minimal, dev, full, always]

- name: "Arch | Allow aur_builder to run sudo pacman without password"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    validate: 'visudo -cf %s'
    create: true
  tags: [minimal, dev, full, always]

- name: "Arch | Install yay"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: makepkg
  tags: [minimal, dev, full, always]

# === PACKAGES ===

- name: "Arch | Install minimal packages"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ minimal.shared + minimal.yay }}"
  when: install_minimal
  tags: [minimal, dev, full]

- name: "Arch | Install dev packages"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ dev.shared + dev.yay }}"
  when: install_dev
  tags: [dev, full]

- name: "Arch | Install full packages"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ full.shared + full.yay }}"
  when: install_full
  tags: [full]

# === CHEZMOI ===

- name: "Arch | Install chezmoi"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: chezmoi
  tags: [minimal, dev, full]

# === CLEANUP ===

- name: "Arch | Remove aur_builder sudoers file"
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: absent
  tags: [minimal, dev, full, always]

- name: "Arch | Remove aur_builder user"
  become: true
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: true
  tags: [minimal, dev, full, always]
