---
# === PREREQUISITES ===

- name: "Ubuntu | System update"
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  tags: [minimal, dev, full, always]

- name: "Ubuntu | Install brew prerequisites"
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - curl
      - procps
      - file
    state: present
  tags: [minimal, dev, full, always]

# === HOMEBREW INSTALL ===

- name: "Brew | Check if Homebrew is installed"
  ansible.builtin.stat:
    path: "{{ brew_bin }}"
  register: brew_installed
  tags: [minimal, dev, full, always]

- name: "Brew | Create linuxbrew directory"
  become: true
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0755"
  when: not brew_installed.stat.exists
  tags: [minimal, dev, full, always]

- name: "Brew | Install Homebrew"
  ansible.builtin.shell:
    cmd: >
      NONINTERACTIVE=1
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_installed.stat.exists
  tags: [minimal, dev, full, always]

- name: "Brew | Add to .bashrc"
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    create: true
  tags: [minimal, dev, full, always]

# === BREW PACKAGES ===

- name: "Brew | Install minimal packages"
  community.general.homebrew:
    name: "{{ minimal.brew }}"
    state: present
    path: "{{ brew_prefix }}/bin"
    update_homebrew: true
  when: install_minimal
  tags: [minimal, dev, full]

- name: "Brew | Install dev packages"
  community.general.homebrew:
    name: "{{ dev.brew }}"
    state: present
    path: "{{ brew_prefix }}/bin"
  when: install_dev
  tags: [dev, full]

- name: "Brew | Install full packages"
  community.general.homebrew:
    name: "{{ full.brew }}"
    state: present
    path: "{{ brew_prefix }}/bin"
  when: install_full
  tags: [full]

# === APT PACKAGES ===

- name: "Ubuntu | Install full packages"
  become: true
  ansible.builtin.apt:
    name: "{{ full.apt }}"
    state: present
  when: install_full and full.apt | length > 0
  tags: [full]

# === CHEZMOI ===

- name: "Brew | Install chezmoi"
  community.general.homebrew:
    name: chezmoi
    state: present
    path: "{{ brew_prefix }}/bin"
  tags: [minimal, dev, full]
