---
- name: "Julia | Add release channel"
  ansible.builtin.command: juliaup add release
  environment:
    PATH: "{{ targets_julia_path }}"
  when: install_dev
  tags: [dev, full]

- name: "Julia | Install app - jetls"
  ansible.builtin.command: >
    julia -e 'using Pkg; Pkg.Apps.add(; url="https://github.com/aviatesk/JETLS.jl", rev="release")'
  environment:
    PATH: "{{ targets_julia_path }}"
  args:
    creates: "~/.julia/bin/jetls"
  when: install_dev
  tags: [dev, full]

- name: "Julia | Install app - jlfmt"
  ansible.builtin.command: >
    julia -e 'using Pkg; Pkg.Apps.add("JuliaFormatter")'
  environment:
    PATH: "{{ targets_julia_path }}"
  args:
    creates: "~/.julia/bin/jlfmt"
  when: install_dev
  tags: [dev, full]

- name: "Julia | Install app - runic"
  ansible.builtin.command: >
    julia -e 'using Pkg; Pkg.Apps.add("Runic")'
  environment:
    PATH: "{{ targets_julia_path }}"
  args:
    creates: "~/.julia/bin/runic"
  when: install_dev
  tags: [dev, full]
