[mgr]
show_hidden = true
show_symlink = true

[opener]
csv = [{ run = 'visidata "$@"', block = true, desc = "visidata" }]
open = [{ run = 'xdg-open "$@"', orphan = true, desc = "open", for = "linux" }]

[open]
prepend_rules = [{ url = "*.csv", use = "csv" }]
